# Generated by Django 5.2.13 on 2026-04-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image')], max_length=10)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
